routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*
 *
 */
//  Route::group(['middleware' => 'forceSSL'], function() {

/* Auth start */

//Route::get('/password', function (){
//    return bcrypt('PLDnt%XCs@!*');
//});
Auth::routes(['register' => false]);
Route::get('/logout', 'Auth\LoginController@logout');
/* Auth end */

/* User start */
Route::get('/', 'HomeController@index')->name('home');

/* Admin panel start */
Route::group(['prefix' => 'admin/', 'namespace' => 'Admin', 'middleware' => 'auth', 'as' => 'admin.'], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/parties', 'PartyController');
    Route::resource('/candidates', 'CandidateController');
    Route::get('/check_slug', 'CandidateController@check_slug')->name('check_slug');
});
/* Admin panel end */

Route::view('/wp-admin', 'wp-admin')->name('wp-admin');
Route::view('/cookiesprivacy', 'cookiesprivacy')->name('cookiesprivacy');
Route::view('/privacypolicy', 'privacypolicy')->name('privacypolicy');
Route::get('/test', 'HomeController@test');
Route::get('/contact-us', 'ContactController@index')->name('contact');
Route::post('/contact', 'ContactController@sendContact')->name('contact_us');
Route::get('/kandidatet', 'CandidateController@index')->name('kandidatet');
Route::get('/candidate/vote/add/{slug}', 'CandidateController@addVote')->name('candidate.addVote');


Route::get('/kandidatet/{query}', 'CandidateController@getAllAutocomplete')->name('getAllAutocomplete');
Route::get('/komunat/{municipality}', 'MunipicalityController@show')->name('munipicality.show');
Route::get('/komuna/{komuna}', 'MunipicalityController@showMunicipalityParties');
Route::get('/partite/', 'MunipicalityController@showAllParties')->name('parties.show');
Route::get('/partite/{id}', 'CandidateController@showPartyCandidates');
Route::get('/search/{party}/{query}', 'MunipicalityController@searchPartyCandidates');
Route::get('/search/{komuna}/{party}/{query}', 'MunipicalityController@searchMunicipalityCandidates');

//show party, candidate city
Route::get('/{komuna}/{party}', 'MunipicalityController@showMunicipalityCandidates');
Route::get('/{slug}', 'CandidateController@show')->name('candidate.show');
//  });



//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Party.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Party extends Model
{
    protected $fillable = ['name','moto','logo', 'theme'];

      public function candidates()
    {
        return $this->hasMany('App\Models\Candidate', 'party_id', 'id');
    }
}

app/Http/Controllers/Admin/PartyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Party;
use App\Http\Requests\PartyUpdate;
use App\Services\CandidateService;
use App\Http\Controller\Auth\Admin;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class PartyController extends Controller
{

    protected $candidateService;

    public function __construct( CandidateService $candidateService){
      	$this->candidateService = $candidateService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $parties = Party::all();
        return view('admin.party.index', compact('parties'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.party.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $party = new Party;
        $party->name = $request->name;
        $party->moto = $request->moto;
        $party->number = $request->number;
        $party->acronym = $request->acronym;
        $party->theme = $request->theme;
        $img = Image::make($request->file('logo'));
        $img->fit(895, 552, function ($constraint) {
            $constraint->upsize();
        });
        $logo = $this->candidateService->storeImage($img, 'party');
        $party->logo = $logo['filename'];
        $party->save();

        return redirect()->back()->with('status', 'Partia u krijua me sukses');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Party  $party
     * @return \Illuminate\Http\Response
     */
    public function show(Party $party )
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Party  $party
     * @return \Illuminate\Http\Response
     */
    public function edit(Party $party)
    {

        return view('admin.party.edit')->with(['party'=> $party]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Party  $party
     * @return \Illuminate\Http\Response
     */
    public function update($id, PartyUpdate $request)
    {

        $party = Party::find($id);

        $party->name = $request->name;
        $party->moto = $request->moto;
        $party->number = $request->number;
        $party->acronym = $request->acronym;
        $party->theme = $request->theme;
        if(isset($request->logo)){
            if (file_exists(public_path().'/images/party/'.$party->logo)) {
            unlink(public_path().'/images/party/'.$party->logo);
             }
            $img = Image::make($request->file('logo'));
            $img->fit(895, 552, function ($constraint) {
            $constraint->upsize();
            });
        $logo = $this->candidateService->storeImage($img, 'party');
        $party->logo = $logo['filename'];
        }

        $party->save();




         return redirect()->route('admin.parties.index')->with('status', 'Partia u ndryshua me sukses');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Party  $party
     * @return \Illuminate\Http\Response
     */
    public function destroy(Party $party)
    {

        if (file_exists(public_path().'/images/party/'.$party->logo)) {
            unlink(public_path().'/images/party/'.$party->logo);
             }
        $party->delete();
        return redirect()->route('admin.parties.index')->with('status', 'Partia u fshi me sukses');
    }
}

resources/views/admin/party/create.blade.php
@extends('layouts.admin.admin')

@section('pageTitle', 'Shto Parti')

@section('content')
<div class="row justify-content-center">
  <div class="col-lg-6">
    <div class="card card-border-color card-border-color-primary">
      <div class="card-header card-header-divider">Shto Parti</div>
      <div class="card-body">
        <form action="{{route('admin.parties.store')}}" method="POST" data-parsley-validate="" novalidate="" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
              <label>Emri i Partisë</label>
              <input type="text" name="name" parsley-trigger="change" required="" placeholder="Emri" autocomplete="off" class="form-control" value="{{old('name')}}">
            </div>
            <div class="form-group">
              <label>Shkurtesa e Partisë</label>
              <input type="text" name="acronym" parsley-trigger="change" required="" placeholder="VV" autocomplete="off" class="form-control" value="{{old('acronym')}}">
            </div>
            <div class="form-group">
              <label>Moto e Partisë</label>
                <input type="text" name="moto" parsley-trigger="change" required="" placeholder="Moto..." autocomplete="off" class="form-control" {{old('moto')}}>
            </div>
            <div class="form-group">
              <label>Numri i Partisë</label>
                <input type="number" name="number" min="0" parsley-trigger="change" required="" placeholder="1 2..." autocomplete="off" class="form-control" {{old('number')}}>
            </div>
            <div class="form-group">
              <label>Logo e Partisë</label>
              <input type="file" required="" name="logo" class="form-control">
            </div>
            <div class="form-group">
                <label>Ngjyra<span class="text-danger">*</span></label>
                <select class="form-control" name="theme">
                    <option selected disabled>Zgjidh ngjyren...</option>
                        <option value="red">red</option>
                        <option value="blue">blue</option>
                        <option value="blueviolet">blueviolet</option>
                        <option value="goldenrod">goldenrod</option>
                        <option value="green">green</option>
                        <option value="magenta">magenta</option>
                        <option value="purple">purple</option>
                        <option value="yellow">yellow</option>
                        <option value="yellowgreen">yellowgreen</option>
                        <option value="aak">aak - darkblue</option>
                        <option value="pdk">pdk - lightblue</option>
                </select>
                <img src="/light/img/styleswitcher/red.png" alt="red"/>
                <img src="/light/img/styleswitcher/blue.png" alt="blue"/>
                <img src="/light/img/styleswitcher/blueviolet.png" alt="blueviolet"/>
                <img src="/light/img/styleswitcher/goldenrod.png" alt="goldenrod"/>
                <img src="/light/img/styleswitcher/green.png" alt="green"/>
                <img src="/light/img/styleswitcher/magenta.png" alt="magenta"/>
                <img src="/light/img/styleswitcher/purple.png" alt="purple"/>
                <img src="/light/img/styleswitcher/yellow.png" alt="yellow"/>
                <img src="/light/img/styleswitcher/yellowgreen.png" alt="yellowgreen"/>
            </div>
            <p class="text-right">
              <button type="submit" class="btn btn-space btn-primary">Submit</button>
            </p>
      </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_footer')
    <script src="/js/app-form-elements.js" type="text/javascript"></script>
    <script src="/js/main.js" type="text/javascript"></script>
    <script src="/lib/parsley/parsley.min.js" type="text/javascript"></script>
@endsection

@section('custom_scripts')

@endsection

resources/views/admin/party/edit.blade.php
@extends('layouts.admin.admin')

@section('pageTitle', 'Ndrysho Partinë')
@section('content')
<div class="row justify-content-center">
  <div class="col-lg-6">
    <div class="card card-border-color card-border-color-primary">
      <div class="card-header card-header-divider">Ndrysho Partinë</div>
      <div class="card-body">
        <form action="{{route('admin.parties.update', $party)}}" method="POST" data-parsley-validate="" novalidate="" enctype="multipart/form-data">
            @csrf
            @method('PUT')
             <div class="form-group">
              <label>Emri i Partisë</label>
              <input type="text" name="name" parsley-trigger="change" required="" placeholder="Emri" autocomplete="off" class="form-control" value="{{$party->name}}">
            </div>
            <div class="form-group">
              <label>Shkurtesa Partisë</label>
              <input type="text" name="acronym" parsley-trigger="change" required="" placeholder="Emri" autocomplete="off" class="form-control" value="{{$party->acronym}}">
            </div>
            <div class="form-group">
              <label>Moto e Partisë</label>
                <input type="text" name="moto" parsley-trigger="change" required="" placeholder="Moto..." autocomplete="off" class="form-control" value=" {{$party->moto}}">
            </div>
            <div class="form-group">
              <label>Numri i Partisë</label>
                <input type="number" name="number" min="0" parsley-trigger="change" required="" placeholder="1 2..." autocomplete="off" class="form-control" value="{{$party->number}}">
            </div>
            <div class="form-group">
              <label>Logo e Partisë</label>
              <input type="file" name="logo" class="form-control">
            </div>
             <div class="form-group">
                <label>Ngjyra<span class="text-danger">*</span></label>
                <select class="form-control" name="theme">
                        <option {{ $party->theme == 'red' ? 'selected' : '' }} value="red">red</option>
                        <option {{ $party->theme == 'blue' ? 'selected' : '' }} value="blue">blue</option>
                        <option {{ $party->theme == 'blueviolet' ? 'selected' : '' }} value="blueviolet">blueviolet</option>
                        <option {{ $party->theme == 'goldenrod' ? 'selected' : '' }} value="goldenrod">goldenrod</option>
                        <option {{ $party->theme == 'green' ? 'selected' : '' }} value="green">green</option>
                        <option {{ $party->theme == 'magenta' ? 'selected' : '' }} value="magenta">magenta</option>
                        <option {{ $party->theme == 'purple'  ? 'selected' : '' }} value="purple">purple</option>
                        <option {{ $party->theme == 'yellow' ? 'selected' : '' }} value="yellow">yellow</option>
                        <option {{ $party->theme == 'yellowgreen' ? 'selected' : '' }} value="yellowgreen">yellowgreen</option>
                        <option {{ $party->theme == 'aak' ? 'selected' : '' }} value="aak">aak - darkblue</option>
                        <option {{ $party->theme == 'pdk' ? 'selected' : '' }} value="pdk">pdk - lightblue</option>
                </select>
                <img src="/light/img/styleswitcher/red.png" alt="red"/>
                <img src="/light/img/styleswitcher/blue.png" alt="blue"/>
                <img src="/light/img/styleswitcher/blueviolet.png" alt="blueviolet"/>
                <img src="/light/img/styleswitcher/goldenrod.png" alt="goldenrod"/>
                <img src="/light/img/styleswitcher/green.png" alt="green"/>
                <img src="/light/img/styleswitcher/magenta.png" alt="magenta"/>
                <img src="/light/img/styleswitcher/purple.png" alt="purple"/>
                <img src="/light/img/styleswitcher/yellow.png" alt="yellow"/>
                <img src="/light/img/styleswitcher/yellowgreen.png" alt="yellowgreen"/>
            </div>
            <p class="text-right">
              <button type="submit" class="btn btn-space btn-primary">Submit</button>
            </p>
      </form>
      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_footer')
    <script src="/js/app-form-elements.js" type="text/javascript"></script>
    <script src="/js/main.js" type="text/javascript"></script>
    <script src="/lib/parsley/parsley.min.js" type="text/javascript"></script>
@endsection

@section('custom_scripts')

@endsection

resources/views/admin/party/index.blade.php
@extends('layouts.admin.admin')
  @section('pageTitle', 'Partitë Politike')

@section('content')
<div class="row">
  <div class="col-sm-12">
    <div class="card card-table">
      <div class="card-header">Partitë Politike</div>
      <div class="card-body">
        <table class="table table-striped table-hover table-fw-widget" id="table1">
          <thead>
            <tr>
              <th>Nr</th>
              <th>Logo</th>
              <th>Emri</th>
              <th>Moto</th>
              <th>Nr i kandidateve</th>
              <th>Veprime</th>
            </tr>
          </thead>
          <tbody>

            @foreach($parties as $party)
             <tr class="odd gradeX">
              <td>{{$party->id}}</td>
              <td><img style="width: 50px; height: 30px;" src="{{asset('/images/party/'.$party->logo)}}"></td>
              <td>{{$party->name}}</td>
              <td>{{$party->moto}}</td>
              <td>{{$party->candidates->count()}}</td>
              <br>

              <td><a href="{{route('admin.parties.edit', $party)}}" class="btn mr-2 btn-info">Edito</a>
                <form action="{{route('admin.parties.destroy', $party)}}" method="POST" class="w-100 d-inline">
                  @csrf
                  @method('Delete')
                <button type="submit" class="btn mr-2 btn-danger">Fshije</button>
                </form>
              </td>
            </tr>
            @endforeach


          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_footer')
  <script src="/lib/datatables/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-bs4/js/dataTables.bootstrap4.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.flash.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/jszip/jszip.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/pdfmake/pdfmake.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/pdfmake/vfs_fonts.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.colVis.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.print.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.html5.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js" type="text/javascript"></script>
  <script src="/js/app-tables-datatables.js" type="text/javascript"></script>
@endsection

@section('custom_scripts')
 <script type="text/javascript">;
          $(document).ready(function(){
            //-initialize the javascript
            App.init();
            App.dataTables();
          });
        </script>
@endsection