routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*
 *
 */
//  Route::group(['middleware' => 'forceSSL'], function() {

/* Auth start */

//Route::get('/password', function (){
//    return bcrypt('PLDnt%XCs@!*');
//});
Auth::routes(['register' => false]);
Route::get('/logout', 'Auth\LoginController@logout');
/* Auth end */

/* User start */
Route::get('/', 'HomeController@index')->name('home');

/* Admin panel start */
Route::group(['prefix' => 'admin/', 'namespace' => 'Admin', 'middleware' => 'auth', 'as' => 'admin.'], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/parties', 'PartyController');
    Route::resource('/candidates', 'CandidateController');
    Route::get('/check_slug', 'CandidateController@check_slug')->name('check_slug');
});
/* Admin panel end */

Route::view('/wp-admin', 'wp-admin')->name('wp-admin');
Route::view('/cookiesprivacy', 'cookiesprivacy')->name('cookiesprivacy');
Route::view('/privacypolicy', 'privacypolicy')->name('privacypolicy');
Route::get('/test', 'HomeController@test');
Route::get('/contact-us', 'ContactController@index')->name('contact');
Route::post('/contact', 'ContactController@sendContact')->name('contact_us');
Route::get('/kandidatet', 'CandidateController@index')->name('kandidatet');
Route::get('/candidate/vote/add/{slug}', 'CandidateController@addVote')->name('candidate.addVote');


Route::get('/kandidatet/{query}', 'CandidateController@getAllAutocomplete')->name('getAllAutocomplete');
Route::get('/komunat/{municipality}', 'MunipicalityController@show')->name('munipicality.show');
Route::get('/komuna/{komuna}', 'MunipicalityController@showMunicipalityParties');
Route::get('/partite/', 'MunipicalityController@showAllParties')->name('parties.show');
Route::get('/partite/{id}', 'CandidateController@showPartyCandidates');
Route::get('/search/{party}/{query}', 'MunipicalityController@searchPartyCandidates');
Route::get('/search/{komuna}/{party}/{query}', 'MunipicalityController@searchMunicipalityCandidates');

//show party, candidate city
Route::get('/{komuna}/{party}', 'MunipicalityController@showMunicipalityCandidates');
Route::get('/{slug}', 'CandidateController@show')->name('candidate.show');
//  });



//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Candidate.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;

class Candidate extends Model
{
     use Sluggable;
    protected $fillable = ['full_name', 'short_bio',
        'gender', 'municipality', 'number', 'party_id', 'ckaban',
        'slug', 'facebook', 'instagram', 'twitter', 'email', 'pcimage', 'phoneimage', 'votes'
 	];

    public function party()
    {
        return $this->belongsTo('App\Models\Party', 'party_id', 'id');
    }
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'full_name'
            ]
        ];
    }
}

app/Http/Controllers/Admin/CandidateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CandidateStoreRequest;
use App\Models\Candidate;
use App\Models\Party;
use App\Services\CandidateService;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Arr;

//use Intervention\Image\Image;

class CandidateController extends Controller
{
    protected $candidateService;

    public function __construct( CandidateService $candidateService){
      	$this->candidateService = $candidateService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $candidates= Candidate::all();
        return view('admin.candidate.index', compact('candidates'));
    }
    public function showPartyCandidates($id){
        dd($id);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parties = Party::all();
        $municipalities = $this->candidateService->getmunicipalities();
        sort($municipalities);
        return view('admin.candidate.create', compact(['parties', 'municipalities']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CandidateStoreRequest $request)
    {

        $candidate = new Candidate;
        $fillableFields = $candidate->getFillable();
        $filteredFields = $this->filterUnwanted(['pcimg', 'phoneimg', 'party_id'], $fillableFields);
        foreach($filteredFields as $field => $value){
            $this->declareIfIsset($value, $request, $candidate);
        }
        //store image for pc
        $pcimage = $this->candidateService->getImage($request->pcimg); // decode base64_decode
        $pcimage = Image::make($pcimage);
        $pcimage = $this->candidateService->storeImage($pcimage, 'pc'); // store image and return filename, directory
        $candidate->pcimage = $pcimage['filename'];

        //store  image for phone
        $phoneimage = $this->candidateService->getImage($request->phoneimg);
        $phoneimage = Image::make($phoneimage);
        $phoneimage = $this->candidateService->storeImage($phoneimage, 'phone'); // store image and return filename, directory
        $candidate->phoneimage = $phoneimage['filename'];

        $candidate->party_id = $request->party_id;
        $candidate->save();

        return redirect()->back()->with('status', 'Kandidati u krijua me sukses');
    }

    public function filterUnwanted(array $fields, $variable)
    {
        $keys = $this->getKeys($fields, $variable);
        return $result = Arr::except($variable, $keys);
    }
    public function getKeys(array $fields, $array)
    {

        $result = array();
        foreach($fields as $field){
            if (in_array($field, $array)){
            $key = array_search( $field, $array );
            $result[] = $key;
            }
        }
        return $result;
    }

    public function declareIfIsset($field, $request, $variableName)
    {
        if (isset($request->$field)){
            $variableName->$field = $request->$field;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
         return redirect()->route('admin.candidate.index' );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $parties = Party::all();
        $municipalities = $this->candidateService->getmunicipalities();
        sort($municipalities);
        $candidate = Candidate::find($id);
        return view('admin.candidate.edit')->with(['candidate' => $candidate , 'municipalities' => $municipalities , 'parties' => $parties ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Candidate $candidate)
    {
        Validator::make($request->all(), [
            'slug' =>  [
                'required',
                 Rule::unique('candidates')->ignore($candidate->id),
            ],
        ]);
        $candidate->slug = Str::slug($request->full_name);
        $fillableFields = $candidate->getFillable();
        $filteredFields = $this->filterUnwanted(['pcimg', 'phoneimg', 'party_id'], $fillableFields);
        foreach($filteredFields as $field => $value){
            $this->declareIfIsset($value, $request, $candidate);
        }

        //delete and store new image if isset
        if (isset($request->pcimg)){
            if (file_exists(public_path().'/images/pc/'.$candidate->pcimage)) {
                unlink(public_path().'/images/pc/'.$candidate->pcimage);
           }
            //store image for pc
            $pcimage = $this->candidateService->getImage($request->pcimg); // decode base64_decode
            $pcimage = Image::make($pcimage);
            $pcimage = $this->candidateService->storeImage($pcimage, 'pc'); // store image and return filename, directory
            $candidate->pcimage = $pcimage['filename'];
        }
        //delete and store new image if isset
        if (isset($request->phoneimg)){
            if (file_exists(public_path().'/images/phone/'.$candidate->phoneimage)) {
                unlink(public_path().'/images/phone/'.$candidate->phoneimage);
            }
        //store  image for phone
        $phoneimage = $this->candidateService->getImage($request->phoneimg);
        $phoneimage = Image::make($phoneimage);
        $phoneimage = $this->candidateService->storeImage($phoneimage, 'phone'); // store image and return filename, directory
        $candidate->phoneimage = $phoneimage['filename'];
        }

        $candidate->party_id = $request->party_id;
        $candidate->save();

        return redirect()->back()->with('status', "Kandidati u ndryshua me sukses");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Candidate $candidate)
    {
            //delete candidate pc image
            if (file_exists(public_path().'/images/pc/'.$candidate->pcimage)) {
                unlink(public_path().'/images/pc/'.$candidate->pcimage);
           }
            //delete candidate phone image
            if (file_exists(public_path() . '/images/phone/' . $candidate->phoneimage)) {
                unlink(public_path() . '/images/phone/' . $candidate->phoneimage);
            }
            $candidate->delete();
           return redirect()->back()->with('status', "Kandidati u fshi me sukses");
    }

    public function check_slug(Request $request)
    {
        if ($request->full_name == ''){
                return response()->json(['slug' => $request->full_name]);
        }
        // New version: to generate unique slugs
        $slug = SlugService::createSlug(Candidate::class, 'slug', $request->full_name);

        return response()->json(['slug' => $slug]);
    }
}

app/Http/Controllers/CandidateController.php
<?php

namespace App\Http\Controllers;

use App\Services\CandidateService;
use App\Models\Party;
use App\Models\Candidate;
use Illuminate\Http\Request;

class CandidateController extends Controller
{
    protected $candidateService;

    public function __construct(CandidateService $candidateService)
    {
        $this->candidateService = $candidateService;
    }

    public function index()
    {
        $candidates = Candidate::orderBy('full_name')->paginate(16);
        return view('candidate.index', compact('candidates'));
    }

    public function showPartyCandidates($id)
    {
        $party = Party::findOrFail($id);
        $candidates = Candidate::whereHas('party', function ($query) use ($party) {
                $query->where('acronym', $party->acronym);
            })->orderByRaw('CONVERT(number, SIGNED) asc')->paginate(16);
        return view('kandidatet', compact(['party', 'candidates']));
    }

    public function show($slug)
    {
        $candidate = $this->candidateService->findCandidateBySlug($slug);
        return view('candidate.show', compact('candidate'));
    }

    public function getAllAutocomplete($query)
    {
        $candidates = Candidate::take(10)->where('full_name', 'like', '%' . $query . '%')
            ->orWhere('municipality', 'like', '%' . $query . '%')
            ->orWhereHas('party', function ($myquery) use ($query) {
                $myquery->where('acronym', 'like', '%' . $query . '%');
            })
            ->orWhereHas('party', function ($myquery) use ($query) {
                $myquery->where('name', 'like', '%' . $query . '%');
            })
            ->get();

        $data = "";
        if ($candidates->count() > 0) {
            foreach ($candidates as $candidate) {
                $data .= '<a class="dropdown-item" href="/' . $candidate->slug . '">' . $candidate->full_name . ' ' . $candidate->party->acronym . ' ' . ucfirst($candidate->municipality) . '</a>';
            }
        }
        return response()->json([$data, 'count' => $candidates->count()]);
    }

    public function addVote($slug)
    {
        $candidate = $this->candidateService->findCandidateBySlug($slug);
        $candidate->increment('votes');
        return redirect()->back();
    }

}

resources/views/admin/candidate/index.blade.php
@extends('layouts.admin.admin')
  @section('pageTitle', 'Kandidatët Politikë')

@section('content')
<div class="row">
  <div class="col-sm-12">
    <div class="card card-table">
      <div class="card-header">Kandidatët Politikë</div>
      <div class="card-body">
        <table class="table table-striped table-hover table-fw-widget" id="table1">
          <thead>
            <tr>
              <th>Nr</th>
              <th>Logo</th>
              <th>Emri & Mbiemri </th>
              <th>Nr. i kandidatit</th>
              <th>Partia</th>
              <th>Veprime</th>
       `     </tr>
          </thead>
          <tbody>

            @foreach($candidates as $candidate)
             <tr class="odd gradeX">
              <td>{{$candidate->id}}</td>

               @if($candidate->party)
              <td><img style="width:50px;height:30px; " src="{{asset('/images/party/'.$candidate->party->logo)}}"></td>
                @else
                 <td style="color: red">null</td>
              @endif
              <td>{{$candidate->full_name}}</td>
              <td>{{$candidate->number}}</td>
              @if($candidate->party)
                 <td>{{$candidate->party->name}}</td>
              @else
                 <td style="color: red">null</td>
              @endif
              <br>

              <td><a href="{{route('admin.candidates.edit', $candidate->id)}}" class="btn mr-2 btn-info">Edito</a>
                <form action="{{route('admin.candidates.destroy', $candidate)}}" method="POST" class="w-100 d-inline">
                  @csrf
                  @method('Delete')
                <button type="submit" class="btn mr-2 btn-danger">Fshije</button>
                </form>
              </td>
            </tr>
            @endforeach


          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_footer')
  <script src="/lib/datatables/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-bs4/js/dataTables.bootstrap4.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.flash.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/jszip/jszip.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/pdfmake/pdfmake.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/pdfmake/vfs_fonts.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.colVis.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.print.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.html5.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js" type="text/javascript"></script>
  <script src="/js/app-tables-datatables.js" type="text/javascript"></script>
@endsection

@section('custom_scripts')
 <script type="text/javascript">;
          $(document).ready(function(){
            //-initialize the javascript
            App.init();
            App.dataTables();
          });
        </script>
@endsection