routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*
 *
 */
//  Route::group(['middleware' => 'forceSSL'], function() {

/* Auth start */

//Route::get('/password', function (){
//    return bcrypt('PLDnt%XCs@!*');
//});
Auth::routes(['register' => false]);
Route::get('/logout', 'Auth\LoginController@logout');
/* Auth end */

/* User start */
Route::get('/', 'HomeController@index')->name('home');

/* Admin panel start */
Route::group(['prefix' => 'admin/', 'namespace' => 'Admin', 'middleware' => 'auth', 'as' => 'admin.'], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/parties', 'PartyController');
    Route::resource('/candidates', 'CandidateController');
    Route::get('/check_slug', 'CandidateController@check_slug')->name('check_slug');
});
/* Admin panel end */

Route::view('/wp-admin', 'wp-admin')->name('wp-admin');
Route::view('/cookiesprivacy', 'cookiesprivacy')->name('cookiesprivacy');
Route::view('/privacypolicy', 'privacypolicy')->name('privacypolicy');
Route::get('/test', 'HomeController@test');
Route::get('/contact-us', 'ContactController@index')->name('contact');
Route::post('/contact', 'ContactController@sendContact')->name('contact_us');
Route::get('/kandidatet', 'CandidateController@index')->name('kandidatet');
Route::get('/candidate/vote/add/{slug}', 'CandidateController@addVote')->name('candidate.addVote');


Route::get('/kandidatet/{query}', 'CandidateController@getAllAutocomplete')->name('getAllAutocomplete');
Route::get('/komunat/{municipality}', 'MunipicalityController@show')->name('munipicality.show');
Route::get('/komuna/{komuna}', 'MunipicalityController@showMunicipalityParties');
Route::get('/partite/', 'MunipicalityController@showAllParties')->name('parties.show');
Route::get('/partite/{id}', 'CandidateController@showPartyCandidates');
Route::get('/search/{party}/{query}', 'MunipicalityController@searchPartyCandidates');
Route::get('/search/{komuna}/{party}/{query}', 'MunipicalityController@searchMunicipalityCandidates');

//show party, candidate city
Route::get('/{komuna}/{party}', 'MunipicalityController@showMunicipalityCandidates');
Route::get('/{slug}', 'CandidateController@show')->name('candidate.show');
//  });



//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/admin/admin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
       <link rel="icon" href="{{asset('img\tagDigitals.png')}}" sizes="32x32">
    <meta name="author" content="Tag Digitals - https://tagdigitals.com/">
    <title>@yield('pageTitle') | Admin</title>
    <link rel="stylesheet" type="text/css" href="/lib/perfect-scrollbar/css/perfect-scrollbar.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jqvmap/jqvmap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
    <link rel="stylesheet" href="/css/app.css" type="text/css"/>
    <style>
        .be-top-header .container-fluid{
            padding: 1px !important;
        }
        .be-top-header .be-navbar-header .navbar-brand{
            background-size: 100% 100%;
            width: 84px !important;
        }
    </style>

    @yield('custom_header')
    @yield('custom_style')
  </head>
    <body>
        <div class="be-wrapper be-fixed-sidebar">
             @include('layouts.admin.header')
             @include('layouts.admin.sidebar')
             <div class="be-content">
                <div class="main-content container-fluid">
                    @include('layouts.admin.notifications')
                    @yield('content')
                </div>
             </div>
        </div>

        <script src="/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="/lib/perfect-scrollbar/js/perfect-scrollbar.min.js" type="text/javascript"></script>
        <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
        <script src="/js/app.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.pie.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.time.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.resize.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.orderBars.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/curvedLines.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.tooltip.js" type="text/javascript"></script>
        <script src="/lib/jquery.sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="/lib/countup/countUp.min.js" type="text/javascript"></script>
        <script src="/lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/jquery.vmap.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="/js/app-dashboard.js" type="text/javascript"></script>

        @yield('custom_footer')
        <script type="text/javascript">;
          $(document).ready(function(){
            //-initialize the javascript
            App.init();
          });
        </script>
        @yield('custom_scripts')
  </body>
</html>

resources/views/layouts/admin/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="{{asset('img\tagDigitals.png')}}" sizes="32x32">
    <title>@yield('pageTitle') | Admin</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
{{--    <link rel="dns-prefetch" href="">--}}
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">

                <div class="be-navbar-header">
                  <a href="/"> <img src="{{asset('img\tagDigitals.png')}}" style="width: 80%"> </a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/admin/header.blade.php
<nav class="navbar navbar-expand fixed-top be-top-header">
  <div class="container-fluid">
    <div class="be-navbar-header">
      <a href="/admin"> <img src="{{asset('img\tagDigitals.png')}}" style="width: 70%"> </a>
    </div>
    <div class="be-right-navbar">
      <ul class="nav navbar-nav float-right be-user-nav">
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false"><img src="/img/avatar.png" alt="Avatar"><span class="user-name">{{Auth::user()->name}}</span></a>
          <div class="dropdown-menu" role="menu">
            <div class="user-info">
              <div class="user-name">{{Auth::user()->name}} </div>
            </div>
              <a class="dropdown-item" href="{{url('/user/edit')}}"><span class="icon mdi mdi-face"></span>Profili</a>

            <a class="dropdown-item" href="{{ url('/logout') }}"><span class="icon mdi mdi-power"></span>Logout</a>
          </div>
        </li>
      </ul>
         <!-- Fixed Navigation Ends -->
    <!-- Mobile Menu Starts -->
    <nav role="navigation" class="d-block d-lg-none">
        <div id="menuToggle">
            <input type="checkbox" />
            <span></span>
            <span></span>
            <span></span>
            <ul class="list-unstyled" id="menu">
                <li class="active"><a href="/light/index-2.html"><i class="fa fa-home"></i><span>Home</span></a></li>
                <li><a href="/light/about.html"><i class="fa fa-user"></i><span>About</span></a></li>
                <li><a href="/light/portfolio.html"><i class="fa fa-folder-open"></i><span>Portfolio</span></a></li>
                <li><a href="/light/contact.html"><i class="fa fa-envelope-open"></i><span>Contact</span></a></li>
                <li><a href="/light/blog.html"><i class="fa fa-comments"></i><span>Blog</span></a></li>
            </ul>
        </div>
    </nav>
    <!-- Mobile Menu Ends -->
    </div>
  </div>
</nav>

resources/views/layouts/admin/notifications.blade.php
<div class="container">
	<div class="row">
	<div class="col-md-12">
	@if (session('status'))
		    <div class="alert alert-success text-center">
				{{session('status')}}
		    </div>
		@endif
		@if (session('error'))
		    <div class="alert alert-danger text-center">
				{{session('error')}}
		    </div>
		@endif
		@if (session('danger'))
		    <div class="alert alert-danger text-center">
				{{session('danger')}}
		    </div>
		@endif
		@if (session('warning'))
		    <div class="alert alert-warning text-center">
				{{session('warning')}}
		    </div>
		@endif
		<!-- MailChimp -->
		@if (session('status-MailChimp'))
			    <div class="alert alert-success text-center">
					{{session('status')}}
			    </div>
			@endif
			@if (session('error-MailChimp'))
			    <div class="alert alert-danger text-center">
					{{session('error')}}
			    </div>
			@endif
	  @if ($errors->any())
	    <div class="alert alert-danger text-center">
	        <ul>
	            @foreach ($errors->all() as $error)
	                <li>{{ $error }}</li>
	            @endforeach
	        </ul>
	    </div>
		@endif
	</div>
</div>
</div>

resources/views/layouts/admin/sidebar.blade.php
<div class="be-left-sidebar">
  <div class="left-sidebar-wrapper"><a class="left-sidebar-toggle" href="/">Paneli Kryesor</a>
    <div class="left-sidebar-spacer">
      <div class="left-sidebar-scroll">
        <div class="left-sidebar-content">
          <ul class="sidebar-elements">
            <li class="divider">Menu</li>
            <li ><a href="/"><i class="icon mdi mdi-view-dashboard"></i><span>Faqja Kryesore</span></a></li>
            <li class="{{ Request::is('admin') ? 'active' : '' }}"><a href="/admin"><i class="icon mdi mdi-home"></i><span>Paneli Kryesor</span></a></li>
            <li class="parent {{ Request::is('admin/parties*') ? 'open active' : '' }}">
              <a href="#"><i class="icon mdi mdi-book"></i><span>Partitë</span></a>
              <ul class="sub-menu">
                <li class="{{ Request::is('admin/parties') ? 'active' : '' }}"><a href="{{route('admin.parties.index')}}">Partitë</a></li>
                <li class="{{ Request::is('admin/parties/create') ? 'active' : '' }}"><a href="{{route('admin.parties.create')}}">Shto</a></li>
              </ul>
            </li>
            <li class="parent {{ Request::is('admin/candidates*') ? 'open' : '' }}"><a href="{{ url('admin.candidates.index') }}"><i class="icon mdi mdi-accounts"></i><span>Kandidatët</span></a>
              <ul class="sub-menu">
                 <li class="{{ Request::is('admin/candidates') ? 'active' : '' }}"><a href="{{route('admin.candidates.index')}}">Kandidatët</a></li>
                <li class="{{ Request::is('admin/candidates/create') ? 'active' : '' }}"><a href="{{route('admin.candidates.create')}}">Shto</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/layouts/admin/user.blade.php
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="Web Geneve - https://www.webgeneve.ch/">
    <title>@yield('pageTitle')</title>
    <link rel="stylesheet" type="text/css" href="/lib/perfect-scrollbar/css/perfect-scrollbar.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jqvmap/jqvmap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
    <link rel="stylesheet" href="/css/app.css" type="text/css"/>
    <style>
        .be-top-header .container-fluid{
            padding: 1px !important;
        }
        .be-top-header .be-navbar-header .navbar-brand{
            background-size: 100% 100%;
            width: 84px !important;
        }
    </style>

    @yield('custom_header')
    @yield('custom_style')
  </head>
    <body>
        <div class="be-wrapper be-fixed-sidebar">
             @include('layouts.admin.header')
             <div class="be-content">
                <div class="main-content container-fluid">
                    @include('layouts.admin.notifications')
                    @yield('content')
                </div>
             </div>
        </div>

        <script src="/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="/lib/perfect-scrollbar/js/perfect-scrollbar.min.js" type="text/javascript"></script>
        <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
        <script src="/js/app.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.pie.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.time.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.resize.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.orderBars.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/curvedLines.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.tooltip.js" type="text/javascript"></script>
        <script src="/lib/jquery.sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="/lib/countup/countUp.min.js" type="text/javascript"></script>
        <script src="/lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/jquery.vmap.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="/js/app-dashboard.js" type="text/javascript"></script>

        @yield('custom_footer')
        @yield('custom_scripts')
  </body>
</html>